# Regenerate R/nvel_data.R from the pinned NVEL Fortran source.
#
# Usage:
# Rscript data-raw/extract_nvel_scaling.R /path/to/nvel

args <- commandArgs(trailingOnly = TRUE)
source_dir <- if (length(args)) {
  args[[1L]]
} else {
  Sys.getenv("NVEL_SOURCE", "path/to/VolumeLibrary")
}
scrib_path <- file.path(source_dir, "scrib.f")
intl_path <- file.path(source_dir, "intl78.f")
required <- c(
  scrib_path, intl_path, file.path(source_dir, "segmnt.f"),
  file.path(source_dir, "numlog.f"), file.path(source_dir, "doyal78.f"),
  file.path(source_dir, "mrules.f")
)
if (any(!file.exists(required))) {
  stop("The pinned NVEL reference directory is incomplete.", call. = FALSE)
}

extract_blocks <- function(text, pattern) {
  blocks <- regmatches(text, gregexpr(pattern, text, perl = TRUE))[[1L]]
  unlist(lapply(blocks, function(block) {
    body <- sub("^[^/]*/", "", block)
    tokens <- regmatches(
      body,
      gregexpr("[-+]?[0-9]+(?:\\.[0-9]*)?", body, perl = TRUE)
    )[[1L]]
    as.double(tokens)
  }), use.names = FALSE)
}

scrib <- paste(readLines(scrib_path, warn = FALSE), collapse = "\n")
factor <- extract_blocks(
  scrib, "DATA \\(FACTOR\\(I\\),I=[^/]*/([^/]*)/"
)
exception <- extract_blocks(
  scrib, "DATA ?\\(EXCEPT\\(I\\),I=[^/]*/([^/]*)/"
)
stopifnot(length(factor) == 132L, length(exception) == 149L)

intl <- scrib
required_intl <- c("0.22", "0.71", "0.905", "LENGTH/4.0")
stopifnot(all(vapply(required_intl, grepl, logical(1L), x = intl, fixed = TRUE)))

format_vector <- function(name, value) {
  lines <- vapply(split(value, ceiling(seq_along(value) / 6)), function(chunk) {
    paste(format(chunk, scientific = FALSE, trim = TRUE), collapse = ", ")
  }, character(1L))
  paste0(name, " <- c(\n  ", paste(lines, collapse = ",\n  "), "\n)\n")
}

header <- c(
  "# Generated by data-raw/extract_nvel_scaling.R. Do not edit by hand.",
  "# Source: FMSC VolumeLibrary commit 38548071d5aa652bb90c7f111f86b427f798a1c9",
  ""
)
output <- paste0(
  paste(header, collapse = "\n"),
  format_vector(".mc_scribner_factor", factor), "\n",
  format_vector(".mc_scribner_exception", exception), "\n",
  ".mc_intl14_constants <- c(quadratic = 0.22, linear = 0.71, adjustment = 0.905)\n"
)
writeLines(output, file.path("R", "nvel_data.R"), useBytes = TRUE)
