# Generate the compiled Region 6 form-class lookup tables from the extracted
# literals in inst/extdata/behre_taper_coefficients.csv.

source_path <- file.path("inst", "extdata", "behre_taper_coefficients.csv")
output_path <- file.path(
  "inst", "include", "merchandiser", "form_class_coefficients.hpp"
)
source <- utils::read.csv(source_path, stringsAsFactors = FALSE)
source <- source[grepl("^FORMCL_", source$routine), , drop = FALSE]

array_lines <- function(name, values, width = 12L) {
  chunks <- split(values, ceiling(seq_along(values) / width))
  body <- vapply(chunks, function(chunk) {
    paste0("    ", paste(chunk, collapse = ", "))
  }, character(1))
  body[-length(body)] <- paste0(body[-length(body)], ",")
  c(
    sprintf("static constexpr int %s[%d] = {", name, length(values)),
    body,
    "};"
  )
}

table_values <- function(routine, target) {
  selected <- source[source$routine == routine & source$target == target, ]
  stopifnot(nrow(selected) > 0L, all(selected$value_type == "numeric"))
  as.integer(selected$value_numeric)
}

species_values <- function(routine) {
  selected <- source[source$routine == routine & source$target == "FIAJSP", ]
  stopifnot(nrow(selected) > 0L, all(selected$value_type == "character"))
  value <- trimws(selected$value_character)
  value[!nzchar(value)] <- "-1"
  as.integer(value)
}

routines <- list(
  bm = c("MALHFC", "OCHOFC", "UMATFC", "WLWHFC"),
  ca = c("ROGRFC", "SISKFC"),
  ec = c("OKANFC", "WENAFC"),
  ni = "COLVFC",
  pn = c("OLYMFC", "SIUSFC"),
  so = c("DESHFC", "FREMFC", "WINEFC"),
  wc = c("GIFPFC", "MBSNFC", "MTHDFC", "UMPQFC", "WILLFC")
)

lines <- c(
  "#ifndef TREEVOLUME_FORM_CLASS_COEFFICIENTS_HPP",
  "#define TREEVOLUME_FORM_CLASS_COEFFICIENTS_HPP",
  "",
  "// Generated by data-raw/form-class-header.R from the literal extraction",
  "// pinned to NVEL commit 38548071d5aa652bb90c7f111f86b427f798a1c9.",
  "namespace treevolume {",
  "namespace form_class_coefficients {",
  ""
)
for (short_name in names(routines)) {
  routine <- paste0("FORMCL_", toupper(short_name))
  species <- species_values(routine)
  lines <- c(lines, array_lines(paste0(short_name, "_species"), species), "")
  for (target in routines[[short_name]]) {
    table_name <- paste0(short_name, "_", tolower(sub("FC$", "", target)))
    values <- table_values(routine, target)
    stopifnot(length(values) == length(species) * 5L)
    lines <- c(lines, array_lines(table_name, values), "")
  }
}
lines <- c(
  lines,
  "}  // namespace form_class_coefficients",
  "}  // namespace treevolume",
  "",
  "#endif"
)
writeLines(lines, output_path, useBytes = TRUE)
