// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mc_profile_lookup_cpp
Rcpp::NumericVector mc_profile_lookup_cpp(Rcpp::IntegerVector offsets, Rcpp::NumericVector height, Rcpp::IntegerVector tree, Rcpp::NumericVector target, Rcpp::NumericVector value);
RcppExport SEXP _merchandiser_mc_profile_lookup_cpp(SEXP offsetsSEXP, SEXP heightSEXP, SEXP treeSEXP, SEXP targetSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type height(heightSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_profile_lookup_cpp(offsets, height, tree, target, value));
    return rcpp_result_gen;
END_RCPP
}
// mc_buck_cpp
Rcpp::List mc_buck_cpp(Rcpp::List products, double quantum, int units, int algorithm, int objective, Rcpp::IntegerVector tree_status, Rcpp::IntegerVector chain_offsets, Rcpp::IntegerVector chain_product, Rcpp::IntegerVector segment_offsets, Rcpp::NumericVector segment_lo, Rcpp::NumericVector segment_hi, Rcpp::IntegerVector boundary_offsets, Rcpp::NumericVector boundaries, Rcpp::IntegerVector profile_offsets, Rcpp::NumericVector profile_height, Rcpp::NumericVector dib, Rcpp::NumericVector dob, Rcpp::NumericVector cum_ib, Rcpp::NumericVector cum_ob, Rcpp::IntegerVector defect_offsets, Rcpp::NumericVector defect_from, Rcpp::NumericVector defect_to, Rcpp::IntegerVector defect_effect, Rcpp::NumericVector defect_percent, Rcpp::IntegerVector defect_product, Rcpp::NumericVector weight_factor, int threads);
RcppExport SEXP _merchandiser_mc_buck_cpp(SEXP productsSEXP, SEXP quantumSEXP, SEXP unitsSEXP, SEXP algorithmSEXP, SEXP objectiveSEXP, SEXP tree_statusSEXP, SEXP chain_offsetsSEXP, SEXP chain_productSEXP, SEXP segment_offsetsSEXP, SEXP segment_loSEXP, SEXP segment_hiSEXP, SEXP boundary_offsetsSEXP, SEXP boundariesSEXP, SEXP profile_offsetsSEXP, SEXP profile_heightSEXP, SEXP dibSEXP, SEXP dobSEXP, SEXP cum_ibSEXP, SEXP cum_obSEXP, SEXP defect_offsetsSEXP, SEXP defect_fromSEXP, SEXP defect_toSEXP, SEXP defect_effectSEXP, SEXP defect_percentSEXP, SEXP defect_productSEXP, SEXP weight_factorSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type products(productsSEXP);
    Rcpp::traits::input_parameter< double >::type quantum(quantumSEXP);
    Rcpp::traits::input_parameter< int >::type units(unitsSEXP);
    Rcpp::traits::input_parameter< int >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< int >::type objective(objectiveSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tree_status(tree_statusSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type chain_offsets(chain_offsetsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type chain_product(chain_productSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type segment_offsets(segment_offsetsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type segment_lo(segment_loSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type segment_hi(segment_hiSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type boundary_offsets(boundary_offsetsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type boundaries(boundariesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type profile_offsets(profile_offsetsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type profile_height(profile_heightSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dib(dibSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dob(dobSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type cum_ib(cum_ibSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type cum_ob(cum_obSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type defect_offsets(defect_offsetsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type defect_from(defect_fromSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type defect_to(defect_toSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type defect_effect(defect_effectSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type defect_percent(defect_percentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type defect_product(defect_productSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type weight_factor(weight_factorSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_buck_cpp(products, quantum, units, algorithm, objective, tree_status, chain_offsets, chain_product, segment_offsets, segment_lo, segment_hi, boundary_offsets, boundaries, profile_offsets, profile_height, dib, dob, cum_ib, cum_ob, defect_offsets, defect_from, defect_to, defect_effect, defect_percent, defect_product, weight_factor, threads));
    return rcpp_result_gen;
END_RCPP
}
// mc_nvel_log_scale_cpp
Rcpp::NumericVector mc_nvel_log_scale_cpp(Rcpp::List products, Rcpp::IntegerVector product_index, Rcpp::NumericVector diameter, Rcpp::NumericVector length);
RcppExport SEXP _merchandiser_mc_nvel_log_scale_cpp(SEXP productsSEXP, SEXP product_indexSEXP, SEXP diameterSEXP, SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type products(productsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type product_index(product_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type diameter(diameterSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_nvel_log_scale_cpp(products, product_index, diameter, length));
    return rcpp_result_gen;
END_RCPP
}
// mc_round_dimension_cpp
Rcpp::NumericVector mc_round_dimension_cpp(Rcpp::NumericVector value, Rcpp::IntegerVector operation, Rcpp::IntegerVector dimension, Rcpp::IntegerVector units);
RcppExport SEXP _merchandiser_mc_round_dimension_cpp(SEXP valueSEXP, SEXP operationSEXP, SEXP dimensionSEXP, SEXP unitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type operation(operationSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dimension(dimensionSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type units(unitsSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_round_dimension_cpp(value, operation, dimension, units));
    return rcpp_result_gen;
END_RCPP
}
// mc_duplicate_map_cpp
Rcpp::List mc_duplicate_map_cpp(Rcpp::List columns, Rcpp::IntegerVector defect_offsets, Rcpp::List defect_columns);
RcppExport SEXP _merchandiser_mc_duplicate_map_cpp(SEXP columnsSEXP, SEXP defect_offsetsSEXP, SEXP defect_columnsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type columns(columnsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type defect_offsets(defect_offsetsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type defect_columns(defect_columnsSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_duplicate_map_cpp(columns, defect_offsets, defect_columns));
    return rcpp_result_gen;
END_RCPP
}
// mc_hash_raw_cpp
int mc_hash_raw_cpp(Rcpp::RawVector value);
RcppExport SEXP _merchandiser_mc_hash_raw_cpp(SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_hash_raw_cpp(value));
    return rcpp_result_gen;
END_RCPP
}
// mc_hash_character_cpp
int mc_hash_character_cpp(Rcpp::CharacterVector value);
RcppExport SEXP _merchandiser_mc_hash_character_cpp(SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_hash_character_cpp(value));
    return rcpp_result_gen;
END_RCPP
}
// mc_expand_index_cpp
Rcpp::List mc_expand_index_cpp(Rcpp::IntegerVector unique_tree, Rcpp::IntegerVector map);
RcppExport SEXP _merchandiser_mc_expand_index_cpp(SEXP unique_treeSEXP, SEXP mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type unique_tree(unique_treeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type map(mapSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_expand_index_cpp(unique_tree, map));
    return rcpp_result_gen;
END_RCPP
}
// mc_provider_open
Rcpp::List mc_provider_open(Rcpp::CharacterVector model_ids);
RcppExport SEXP _merchandiser_mc_provider_open(SEXP model_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type model_ids(model_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_provider_open(model_ids));
    return rcpp_result_gen;
END_RCPP
}
// mc_provider_query
Rcpp::List mc_provider_query(SEXP pointer, Rcpp::NumericVector dbh, Rcpp::NumericVector ht, Rcpp::IntegerVector model_index, Rcpp::List aux, Rcpp::IntegerVector tree_index, Rcpp::NumericVector height, int caller_units, bool need_dob, bool need_cum_ob);
RcppExport SEXP _merchandiser_mc_provider_query(SEXP pointerSEXP, SEXP dbhSEXP, SEXP htSEXP, SEXP model_indexSEXP, SEXP auxSEXP, SEXP tree_indexSEXP, SEXP heightSEXP, SEXP caller_unitsSEXP, SEXP need_dobSEXP, SEXP need_cum_obSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ht(htSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type model_index(model_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type aux(auxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tree_index(tree_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type height(heightSEXP);
    Rcpp::traits::input_parameter< int >::type caller_units(caller_unitsSEXP);
    Rcpp::traits::input_parameter< bool >::type need_dob(need_dobSEXP);
    Rcpp::traits::input_parameter< bool >::type need_cum_ob(need_cum_obSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_provider_query(pointer, dbh, ht, model_index, aux, tree_index, height, caller_units, need_dob, need_cum_ob));
    return rcpp_result_gen;
END_RCPP
}
// mc_provider_crossings
Rcpp::List mc_provider_crossings(SEXP pointer, Rcpp::NumericVector dbh, Rcpp::NumericVector ht, Rcpp::IntegerVector model_index, Rcpp::List aux, Rcpp::NumericVector target, Rcpp::IntegerVector bark_basis, Rcpp::NumericVector lower, Rcpp::NumericVector upper, int caller_units);
RcppExport SEXP _merchandiser_mc_provider_crossings(SEXP pointerSEXP, SEXP dbhSEXP, SEXP htSEXP, SEXP model_indexSEXP, SEXP auxSEXP, SEXP targetSEXP, SEXP bark_basisSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP caller_unitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ht(htSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type model_index(model_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type aux(auxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type bark_basis(bark_basisSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type caller_units(caller_unitsSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_provider_crossings(pointer, dbh, ht, model_index, aux, target, bark_basis, lower, upper, caller_units));
    return rcpp_result_gen;
END_RCPP
}
// mc_provider_green_weight
Rcpp::List mc_provider_green_weight(Rcpp::NumericVector volume, Rcpp::IntegerVector spcd, Rcpp::IntegerVector bark_basis, int caller_units);
RcppExport SEXP _merchandiser_mc_provider_green_weight(SEXP volumeSEXP, SEXP spcdSEXP, SEXP bark_basisSEXP, SEXP caller_unitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type volume(volumeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type spcd(spcdSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type bark_basis(bark_basisSEXP);
    Rcpp::traits::input_parameter< int >::type caller_units(caller_unitsSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_provider_green_weight(volume, spcd, bark_basis, caller_units));
    return rcpp_result_gen;
END_RCPP
}
// mc_provider_generation
double mc_provider_generation(SEXP pointer);
RcppExport SEXP _merchandiser_mc_provider_generation(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_provider_generation(pointer));
    return rcpp_result_gen;
END_RCPP
}
// mc_provider_close
void mc_provider_close(SEXP pointer);
RcppExport SEXP _merchandiser_mc_provider_close(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    mc_provider_close(pointer);
    return R_NilValue;
END_RCPP
}
// tv_cpp_kernel_exists
bool tv_cpp_kernel_exists(const std::string& kernel);
RcppExport SEXP _merchandiser_tv_cpp_kernel_exists(SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(tv_cpp_kernel_exists(kernel));
    return rcpp_result_gen;
END_RCPP
}
// tv_cpp_duplicate_map_impl
Rcpp::List tv_cpp_duplicate_map_impl(Rcpp::NumericVector dbh, Rcpp::NumericVector ht, Rcpp::NumericVector x1, Rcpp::NumericVector x2, Rcpp::NumericVector bark_ratio, Rcpp::NumericVector upper_ht1, Rcpp::NumericVector upper_d1, Rcpp::NumericVector upper_ht2, Rcpp::NumericVector upper_d2, Rcpp::IntegerVector upper_bark, Rcpp::NumericVector site_index, Rcpp::NumericVector basal_area, Rcpp::NumericVector form_class);
RcppExport SEXP _merchandiser_tv_cpp_duplicate_map_impl(SEXP dbhSEXP, SEXP htSEXP, SEXP x1SEXP, SEXP x2SEXP, SEXP bark_ratioSEXP, SEXP upper_ht1SEXP, SEXP upper_d1SEXP, SEXP upper_ht2SEXP, SEXP upper_d2SEXP, SEXP upper_barkSEXP, SEXP site_indexSEXP, SEXP basal_areaSEXP, SEXP form_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ht(htSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type bark_ratio(bark_ratioSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_ht1(upper_ht1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_d1(upper_d1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_ht2(upper_ht2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_d2(upper_d2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type upper_bark(upper_barkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type site_index(site_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type basal_area(basal_areaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type form_class(form_classSEXP);
    rcpp_result_gen = Rcpp::wrap(tv_cpp_duplicate_map_impl(dbh, ht, x1, x2, bark_ratio, upper_ht1, upper_d1, upper_ht2, upper_d2, upper_bark, site_index, basal_area, form_class));
    return rcpp_result_gen;
END_RCPP
}
// tv_cpp_profile_grid_impl
Rcpp::List tv_cpp_profile_grid_impl(Rcpp::NumericVector lower, Rcpp::NumericVector upper, Rcpp::NumericVector step, Rcpp::IntegerVector tree_status, int threads);
RcppExport SEXP _merchandiser_tv_cpp_profile_grid_impl(SEXP lowerSEXP, SEXP upperSEXP, SEXP stepSEXP, SEXP tree_statusSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type step(stepSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tree_status(tree_statusSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(tv_cpp_profile_grid_impl(lower, upper, step, tree_status, threads));
    return rcpp_result_gen;
END_RCPP
}
// tv_cpp_kernel_eval_impl
Rcpp::List tv_cpp_kernel_eval_impl(const std::string& kernel_name, int operation, Rcpp::NumericVector dbh, Rcpp::NumericVector ht, Rcpp::NumericVector x1, Rcpp::NumericVector x2, Rcpp::NumericVector bark_ratio, Rcpp::NumericVector upper_ht1, Rcpp::NumericVector upper_d1, Rcpp::NumericVector upper_ht2, Rcpp::NumericVector upper_d2, Rcpp::IntegerVector upper_bark, Rcpp::NumericVector site_index, Rcpp::NumericVector basal_area, Rcpp::NumericVector form_class, Rcpp::NumericVector coefficients, bool nvel_compat, int threads);
RcppExport SEXP _merchandiser_tv_cpp_kernel_eval_impl(SEXP kernel_nameSEXP, SEXP operationSEXP, SEXP dbhSEXP, SEXP htSEXP, SEXP x1SEXP, SEXP x2SEXP, SEXP bark_ratioSEXP, SEXP upper_ht1SEXP, SEXP upper_d1SEXP, SEXP upper_ht2SEXP, SEXP upper_d2SEXP, SEXP upper_barkSEXP, SEXP site_indexSEXP, SEXP basal_areaSEXP, SEXP form_classSEXP, SEXP coefficientsSEXP, SEXP nvel_compatSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type kernel_name(kernel_nameSEXP);
    Rcpp::traits::input_parameter< int >::type operation(operationSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ht(htSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type bark_ratio(bark_ratioSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_ht1(upper_ht1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_d1(upper_d1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_ht2(upper_ht2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_d2(upper_d2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type upper_bark(upper_barkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type site_index(site_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type basal_area(basal_areaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type form_class(form_classSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< bool >::type nvel_compat(nvel_compatSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(tv_cpp_kernel_eval_impl(kernel_name, operation, dbh, ht, x1, x2, bark_ratio, upper_ht1, upper_d1, upper_ht2, upper_d2, upper_bark, site_index, basal_area, form_class, coefficients, nvel_compat, threads));
    return rcpp_result_gen;
END_RCPP
}
// tv_cpp_profile_eval_impl
Rcpp::List tv_cpp_profile_eval_impl(const std::string& kernel_name, Rcpp::IntegerVector tree, Rcpp::NumericVector height, Rcpp::IntegerVector initial_status, Rcpp::NumericVector dbh, Rcpp::NumericVector ht, Rcpp::NumericVector lower, Rcpp::NumericVector bark_ratio, Rcpp::NumericVector upper_ht1, Rcpp::NumericVector upper_d1, Rcpp::NumericVector upper_ht2, Rcpp::NumericVector upper_d2, Rcpp::IntegerVector upper_bark, Rcpp::NumericVector site_index, Rcpp::NumericVector basal_area, Rcpp::NumericVector form_class, Rcpp::NumericVector coefficients, bool nvel_compat, int threads);
RcppExport SEXP _merchandiser_tv_cpp_profile_eval_impl(SEXP kernel_nameSEXP, SEXP treeSEXP, SEXP heightSEXP, SEXP initial_statusSEXP, SEXP dbhSEXP, SEXP htSEXP, SEXP lowerSEXP, SEXP bark_ratioSEXP, SEXP upper_ht1SEXP, SEXP upper_d1SEXP, SEXP upper_ht2SEXP, SEXP upper_d2SEXP, SEXP upper_barkSEXP, SEXP site_indexSEXP, SEXP basal_areaSEXP, SEXP form_classSEXP, SEXP coefficientsSEXP, SEXP nvel_compatSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type kernel_name(kernel_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type height(heightSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type initial_status(initial_statusSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ht(htSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type bark_ratio(bark_ratioSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_ht1(upper_ht1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_d1(upper_d1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_ht2(upper_ht2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper_d2(upper_d2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type upper_bark(upper_barkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type site_index(site_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type basal_area(basal_areaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type form_class(form_classSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< bool >::type nvel_compat(nvel_compatSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(tv_cpp_profile_eval_impl(kernel_name, tree, height, initial_status, dbh, ht, lower, bark_ratio, upper_ht1, upper_d1, upper_ht2, upper_d2, upper_bark, site_index, basal_area, form_class, coefficients, nvel_compat, threads));
    return rcpp_result_gen;
END_RCPP
}
// tv_cpp_nsvb_biomass_impl
Rcpp::List tv_cpp_nsvb_biomass_impl(Rcpp::NumericVector dbh, Rcpp::NumericVector ht, Rcpp::IntegerVector spcd, Rcpp::IntegerVector division, Rcpp::IntegerVector region, Rcpp::IntegerVector forest, Rcpp::IntegerVector decay_class, Rcpp::NumericVector cull, Rcpp::NumericVector primary_top, Rcpp::NumericVector secondary_top, Rcpp::NumericVector stump, Rcpp::NumericVector max_log_length, Rcpp::NumericVector min_log_length, Rcpp::NumericVector minimum_top_length, Rcpp::NumericVector merchantable_length, Rcpp::NumericVector trim, Rcpp::IntegerVector even_or_odd, Rcpp::IntegerVector option, Rcpp::IntegerVector corrected_scribner, Rcpp::IntegerVector ctype, int threads);
RcppExport SEXP _merchandiser_tv_cpp_nsvb_biomass_impl(SEXP dbhSEXP, SEXP htSEXP, SEXP spcdSEXP, SEXP divisionSEXP, SEXP regionSEXP, SEXP forestSEXP, SEXP decay_classSEXP, SEXP cullSEXP, SEXP primary_topSEXP, SEXP secondary_topSEXP, SEXP stumpSEXP, SEXP max_log_lengthSEXP, SEXP min_log_lengthSEXP, SEXP minimum_top_lengthSEXP, SEXP merchantable_lengthSEXP, SEXP trimSEXP, SEXP even_or_oddSEXP, SEXP optionSEXP, SEXP corrected_scribnerSEXP, SEXP ctypeSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ht(htSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type spcd(spcdSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type division(divisionSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type region(regionSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type decay_class(decay_classSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type cull(cullSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type primary_top(primary_topSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type secondary_top(secondary_topSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type stump(stumpSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type max_log_length(max_log_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type min_log_length(min_log_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type minimum_top_length(minimum_top_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type merchantable_length(merchantable_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type trim(trimSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type even_or_odd(even_or_oddSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type option(optionSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type corrected_scribner(corrected_scribnerSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ctype(ctypeSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(tv_cpp_nsvb_biomass_impl(dbh, ht, spcd, division, region, forest, decay_class, cull, primary_top, secondary_top, stump, max_log_length, min_log_length, minimum_top_length, merchantable_length, trim, even_or_odd, option, corrected_scribner, ctype, threads));
    return rcpp_result_gen;
END_RCPP
}
// tv_cpp_nsvb_carbon_fraction_impl
Rcpp::NumericVector tv_cpp_nsvb_carbon_fraction_impl(Rcpp::IntegerVector spcd, bool raw);
RcppExport SEXP _merchandiser_tv_cpp_nsvb_carbon_fraction_impl(SEXP spcdSEXP, SEXP rawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type spcd(spcdSEXP);
    Rcpp::traits::input_parameter< bool >::type raw(rawSEXP);
    rcpp_result_gen = Rcpp::wrap(tv_cpp_nsvb_carbon_fraction_impl(spcd, raw));
    return rcpp_result_gen;
END_RCPP
}
// tv_cpp_nsvb_division_xy_impl
Rcpp::IntegerVector tv_cpp_nsvb_division_xy_impl(Rcpp::NumericVector x, Rcpp::NumericVector y, Rcpp::IntegerVector division, Rcpp::IntegerVector ring_id, Rcpp::LogicalVector hole, Rcpp::NumericVector polygon_x, Rcpp::NumericVector polygon_y, int threads);
RcppExport SEXP _merchandiser_tv_cpp_nsvb_division_xy_impl(SEXP xSEXP, SEXP ySEXP, SEXP divisionSEXP, SEXP ring_idSEXP, SEXP holeSEXP, SEXP polygon_xSEXP, SEXP polygon_ySEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type division(divisionSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ring_id(ring_idSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type hole(holeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type polygon_x(polygon_xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type polygon_y(polygon_ySEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(tv_cpp_nsvb_division_xy_impl(x, y, division, ring_id, hole, polygon_x, polygon_y, threads));
    return rcpp_result_gen;
END_RCPP
}
// stem_provider_probe
Rcpp::List stem_provider_probe(Rcpp::CharacterVector ids, Rcpp::NumericVector dbh, Rcpp::NumericVector ht, Rcpp::IntegerVector tree_index, Rcpp::NumericVector height, Rcpp::NumericVector crossing_target, Rcpp::IntegerVector crossing_basis, Rcpp::NumericVector crossing_lower, Rcpp::NumericVector crossing_upper, Rcpp::NumericVector weight_volume, Rcpp::IntegerVector weight_spcd, Rcpp::IntegerVector weight_basis, Rcpp::IntegerVector weight_component, Rcpp::IntegerVector weight_moisture);
RcppExport SEXP _merchandiser_stem_provider_probe(SEXP idsSEXP, SEXP dbhSEXP, SEXP htSEXP, SEXP tree_indexSEXP, SEXP heightSEXP, SEXP crossing_targetSEXP, SEXP crossing_basisSEXP, SEXP crossing_lowerSEXP, SEXP crossing_upperSEXP, SEXP weight_volumeSEXP, SEXP weight_spcdSEXP, SEXP weight_basisSEXP, SEXP weight_componentSEXP, SEXP weight_moistureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dbh(dbhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ht(htSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tree_index(tree_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type height(heightSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type crossing_target(crossing_targetSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type crossing_basis(crossing_basisSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type crossing_lower(crossing_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type crossing_upper(crossing_upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type weight_volume(weight_volumeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type weight_spcd(weight_spcdSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type weight_basis(weight_basisSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type weight_component(weight_componentSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type weight_moisture(weight_moistureSEXP);
    rcpp_result_gen = Rcpp::wrap(stem_provider_probe(ids, dbh, ht, tree_index, height, crossing_target, crossing_basis, crossing_lower, crossing_upper, weight_volume, weight_spcd, weight_basis, weight_component, weight_moisture));
    return rcpp_result_gen;
END_RCPP
}
// treevolume_toolchain_check
double treevolume_toolchain_check();
RcppExport SEXP _merchandiser_treevolume_toolchain_check() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(treevolume_toolchain_check());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_merchandiser_mc_profile_lookup_cpp", (DL_FUNC) &_merchandiser_mc_profile_lookup_cpp, 5},
    {"_merchandiser_mc_buck_cpp", (DL_FUNC) &_merchandiser_mc_buck_cpp, 27},
    {"_merchandiser_mc_nvel_log_scale_cpp", (DL_FUNC) &_merchandiser_mc_nvel_log_scale_cpp, 4},
    {"_merchandiser_mc_round_dimension_cpp", (DL_FUNC) &_merchandiser_mc_round_dimension_cpp, 4},
    {"_merchandiser_mc_duplicate_map_cpp", (DL_FUNC) &_merchandiser_mc_duplicate_map_cpp, 3},
    {"_merchandiser_mc_hash_raw_cpp", (DL_FUNC) &_merchandiser_mc_hash_raw_cpp, 1},
    {"_merchandiser_mc_hash_character_cpp", (DL_FUNC) &_merchandiser_mc_hash_character_cpp, 1},
    {"_merchandiser_mc_expand_index_cpp", (DL_FUNC) &_merchandiser_mc_expand_index_cpp, 2},
    {"_merchandiser_mc_provider_open", (DL_FUNC) &_merchandiser_mc_provider_open, 1},
    {"_merchandiser_mc_provider_query", (DL_FUNC) &_merchandiser_mc_provider_query, 10},
    {"_merchandiser_mc_provider_crossings", (DL_FUNC) &_merchandiser_mc_provider_crossings, 10},
    {"_merchandiser_mc_provider_green_weight", (DL_FUNC) &_merchandiser_mc_provider_green_weight, 4},
    {"_merchandiser_mc_provider_generation", (DL_FUNC) &_merchandiser_mc_provider_generation, 1},
    {"_merchandiser_mc_provider_close", (DL_FUNC) &_merchandiser_mc_provider_close, 1},
    {"_merchandiser_tv_cpp_kernel_exists", (DL_FUNC) &_merchandiser_tv_cpp_kernel_exists, 1},
    {"_merchandiser_tv_cpp_duplicate_map_impl", (DL_FUNC) &_merchandiser_tv_cpp_duplicate_map_impl, 13},
    {"_merchandiser_tv_cpp_profile_grid_impl", (DL_FUNC) &_merchandiser_tv_cpp_profile_grid_impl, 5},
    {"_merchandiser_tv_cpp_kernel_eval_impl", (DL_FUNC) &_merchandiser_tv_cpp_kernel_eval_impl, 18},
    {"_merchandiser_tv_cpp_profile_eval_impl", (DL_FUNC) &_merchandiser_tv_cpp_profile_eval_impl, 19},
    {"_merchandiser_tv_cpp_nsvb_biomass_impl", (DL_FUNC) &_merchandiser_tv_cpp_nsvb_biomass_impl, 21},
    {"_merchandiser_tv_cpp_nsvb_carbon_fraction_impl", (DL_FUNC) &_merchandiser_tv_cpp_nsvb_carbon_fraction_impl, 2},
    {"_merchandiser_tv_cpp_nsvb_division_xy_impl", (DL_FUNC) &_merchandiser_tv_cpp_nsvb_division_xy_impl, 8},
    {"_merchandiser_stem_provider_probe", (DL_FUNC) &_merchandiser_stem_provider_probe, 14},
    {"_merchandiser_treevolume_toolchain_check", (DL_FUNC) &_merchandiser_treevolume_toolchain_check, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_merchandiser(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
