# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mc_simple_plan_cpp <- function(products, quantum, tree_status, chain_offsets, chain_product, stump, top, ht, threads) {
    .Call(`_merchandiser_mc_simple_plan_cpp`, products, quantum, tree_status, chain_offsets, chain_product, stump, top, ht, threads)
}

mc_profile_lookup_cpp <- function(offsets, height, tree, target, value) {
    .Call(`_merchandiser_mc_profile_lookup_cpp`, offsets, height, tree, target, value)
}

mc_buck_cpp <- function(products, quantum, units, algorithm, objective, tree_status, chain_offsets, chain_product, segment_offsets, segment_lo, segment_hi, boundary_offsets, boundaries, profile_offsets, profile_height, dib, dob, cum_ib, cum_ob, defect_offsets, defect_from, defect_to, defect_effect, defect_percent, defect_category_rank, weight_factor, threads) {
    .Call(`_merchandiser_mc_buck_cpp`, products, quantum, units, algorithm, objective, tree_status, chain_offsets, chain_product, segment_offsets, segment_lo, segment_hi, boundary_offsets, boundaries, profile_offsets, profile_height, dib, dob, cum_ib, cum_ob, defect_offsets, defect_from, defect_to, defect_effect, defect_percent, defect_category_rank, weight_factor, threads)
}

mc_nvel_log_scale_cpp <- function(products, product_index, diameter, length) {
    .Call(`_merchandiser_mc_nvel_log_scale_cpp`, products, product_index, diameter, length)
}

mc_round_dimension_cpp <- function(value, operation, dimension, units) {
    .Call(`_merchandiser_mc_round_dimension_cpp`, value, operation, dimension, units)
}

mc_duplicate_map_cpp <- function(columns, defect_offsets, defect_columns) {
    .Call(`_merchandiser_mc_duplicate_map_cpp`, columns, defect_offsets, defect_columns)
}

mc_hash_raw_cpp <- function(value) {
    .Call(`_merchandiser_mc_hash_raw_cpp`, value)
}

mc_hash_character_cpp <- function(value) {
    .Call(`_merchandiser_mc_hash_character_cpp`, value)
}

mc_expand_index_cpp <- function(unique_tree, map) {
    .Call(`_merchandiser_mc_expand_index_cpp`, unique_tree, map)
}

mc_provider_open <- function(model_ids) {
    .Call(`_merchandiser_mc_provider_open`, model_ids)
}

mc_provider_query <- function(pointer, dbh, ht, model_index, aux, tree_index, height, caller_units, need_dob = TRUE, need_cum_ob = TRUE) {
    .Call(`_merchandiser_mc_provider_query`, pointer, dbh, ht, model_index, aux, tree_index, height, caller_units, need_dob, need_cum_ob)
}

mc_provider_crossings <- function(pointer, dbh, ht, model_index, aux, target, bark_basis, lower, upper, caller_units) {
    .Call(`_merchandiser_mc_provider_crossings`, pointer, dbh, ht, model_index, aux, target, bark_basis, lower, upper, caller_units)
}

mc_provider_green_weight <- function(volume, spcd, bark_basis, caller_units) {
    .Call(`_merchandiser_mc_provider_green_weight`, volume, spcd, bark_basis, caller_units)
}

mc_provider_generation <- function(pointer) {
    .Call(`_merchandiser_mc_provider_generation`, pointer)
}

mc_provider_close <- function(pointer) {
    invisible(.Call(`_merchandiser_mc_provider_close`, pointer))
}

tv_cpp_kernel_exists <- function(kernel) {
    .Call(`_merchandiser_tv_cpp_kernel_exists`, kernel)
}

tv_cpp_duplicate_map_impl <- function(dbh, ht, x1, x2, bark_ratio, upper_ht1, upper_d1, upper_ht2, upper_d2, upper_bark, site_index, basal_area, form_class) {
    .Call(`_merchandiser_tv_cpp_duplicate_map_impl`, dbh, ht, x1, x2, bark_ratio, upper_ht1, upper_d1, upper_ht2, upper_d2, upper_bark, site_index, basal_area, form_class)
}

tv_cpp_profile_grid_impl <- function(lower, upper, step, tree_status, threads) {
    .Call(`_merchandiser_tv_cpp_profile_grid_impl`, lower, upper, step, tree_status, threads)
}

tv_cpp_kernel_eval_impl <- function(kernel_name, operation, dbh, ht, x1, x2, bark_ratio, upper_ht1, upper_d1, upper_ht2, upper_d2, upper_bark, site_index, basal_area, form_class, coefficients, nvel_compat, threads) {
    .Call(`_merchandiser_tv_cpp_kernel_eval_impl`, kernel_name, operation, dbh, ht, x1, x2, bark_ratio, upper_ht1, upper_d1, upper_ht2, upper_d2, upper_bark, site_index, basal_area, form_class, coefficients, nvel_compat, threads)
}

tv_cpp_profile_eval_impl <- function(kernel_name, tree, height, initial_status, dbh, ht, lower, bark_ratio, upper_ht1, upper_d1, upper_ht2, upper_d2, upper_bark, site_index, basal_area, form_class, coefficients, nvel_compat, threads) {
    .Call(`_merchandiser_tv_cpp_profile_eval_impl`, kernel_name, tree, height, initial_status, dbh, ht, lower, bark_ratio, upper_ht1, upper_d1, upper_ht2, upper_d2, upper_bark, site_index, basal_area, form_class, coefficients, nvel_compat, threads)
}

tv_cpp_nsvb_biomass_impl <- function(dbh, ht, spcd, division, region, forest, decay_class, cull, primary_top, secondary_top, stump, max_log_length, min_log_length, minimum_top_length, merchantable_length, trim, even_or_odd, option, corrected_scribner, ctype, threads) {
    .Call(`_merchandiser_tv_cpp_nsvb_biomass_impl`, dbh, ht, spcd, division, region, forest, decay_class, cull, primary_top, secondary_top, stump, max_log_length, min_log_length, minimum_top_length, merchantable_length, trim, even_or_odd, option, corrected_scribner, ctype, threads)
}

tv_cpp_nsvb_carbon_fraction_impl <- function(spcd, raw) {
    .Call(`_merchandiser_tv_cpp_nsvb_carbon_fraction_impl`, spcd, raw)
}

tv_cpp_nsvb_division_xy_impl <- function(x, y, division, ring_id, hole, polygon_x, polygon_y, threads) {
    .Call(`_merchandiser_tv_cpp_nsvb_division_xy_impl`, x, y, division, ring_id, hole, polygon_x, polygon_y, threads)
}

stem_provider_probe <- function(ids, dbh, ht, tree_index, height, crossing_target, crossing_basis, crossing_lower, crossing_upper, weight_volume, weight_spcd, weight_basis, weight_component, weight_moisture) {
    .Call(`_merchandiser_stem_provider_probe`, ids, dbh, ht, tree_index, height, crossing_target, crossing_basis, crossing_lower, crossing_upper, weight_volume, weight_spcd, weight_basis, weight_component, weight_moisture)
}

treevolume_toolchain_check <- function() {
    .Call(`_merchandiser_treevolume_toolchain_check`)
}

